//**********************************************************************`
//* This is an include file generated by Message Compiler.             *`
//*                                                                    *`
//* Copyright (c) Microsoft Corporation. All Rights Reserved.          *`
//**********************************************************************`
#pragma once
#include <wmistr.h>
#include <evntrace.h>
#include "evntprov.h"
//
//  Initial Defs
//
#if !defined(ETW_INLINE)
#define ETW_INLINE DECLSPEC_NOINLINE __inline
#endif

#if defined(__cplusplus)
extern "C" {
#endif

//
// Allow disabling of code generation
//
#ifndef MCGEN_DISABLE_PROVIDER_CODE_GENERATION
#if  !defined(McGenDebug)
#define McGenDebug(a,b)
#endif 


#if !defined(MCGEN_TRACE_CONTEXT_DEF)
#define MCGEN_TRACE_CONTEXT_DEF
typedef struct _MCGEN_TRACE_CONTEXT
{
    TRACEHANDLE            RegistrationHandle;
    TRACEHANDLE            Logger;
    ULONGLONG              MatchAnyKeyword;
    ULONGLONG              MatchAllKeyword;
    ULONG                  Flags;
    ULONG                  IsEnabled;
    UCHAR                  Level; 
    UCHAR                  Reserve;
    USHORT                 EnableBitsCount;
    PULONG                 EnableBitMask;
    const ULONGLONG*       EnableKeyWords;
    const UCHAR*           EnableLevel;
} MCGEN_TRACE_CONTEXT, *PMCGEN_TRACE_CONTEXT;
#endif

#if !defined(MCGEN_LEVEL_KEYWORD_ENABLED_DEF)
#define MCGEN_LEVEL_KEYWORD_ENABLED_DEF
FORCEINLINE
BOOLEAN
McGenLevelKeywordEnabled(
    _In_ PMCGEN_TRACE_CONTEXT EnableInfo,
    _In_ UCHAR Level,
    _In_ ULONGLONG Keyword
    )
{
    //
    // Check if the event Level is lower than the level at which
    // the channel is enabled.
    // If the event Level is 0 or the channel is enabled at level 0,
    // all levels are enabled.
    //

    if ((Level <= EnableInfo->Level) || // This also covers the case of Level == 0.
        (EnableInfo->Level == 0)) {

        //
        // Check if Keyword is enabled
        //

        if ((Keyword == (ULONGLONG)0) ||
            ((Keyword & EnableInfo->MatchAnyKeyword) &&
             ((Keyword & EnableInfo->MatchAllKeyword) == EnableInfo->MatchAllKeyword))) {
            return TRUE;
        }
    }

    return FALSE;

}
#endif

#if !defined(MCGEN_EVENT_ENABLED_DEF)
#define MCGEN_EVENT_ENABLED_DEF
FORCEINLINE
BOOLEAN
McGenEventEnabled(
    _In_ PMCGEN_TRACE_CONTEXT EnableInfo,
    _In_ PCEVENT_DESCRIPTOR EventDescriptor
    )
{

    return McGenLevelKeywordEnabled(EnableInfo, EventDescriptor->Level, EventDescriptor->Keyword);

}
#endif


//
// EnableCheckMacro
//
#ifndef MCGEN_ENABLE_CHECK
#define MCGEN_ENABLE_CHECK(Context, Descriptor) (Context.IsEnabled &&  McGenEventEnabled(&Context, &Descriptor))
#endif

#if !defined(MCGEN_CONTROL_CALLBACK)
#define MCGEN_CONTROL_CALLBACK

DECLSPEC_NOINLINE __inline
VOID
__stdcall
McGenControlCallbackV2(
    _In_ LPCGUID SourceId,
    _In_ ULONG ControlCode,
    _In_ UCHAR Level,
    _In_ ULONGLONG MatchAnyKeyword,
    _In_ ULONGLONG MatchAllKeyword,
    _In_opt_ PEVENT_FILTER_DESCRIPTOR FilterData,
    _Inout_opt_ PVOID CallbackContext
    )
/*++

Routine Description:

    This is the notification callback for Windows Vista and later.

Arguments:

    SourceId - The GUID that identifies the session that enabled the provider. 

    ControlCode - The parameter indicates whether the provider 
                  is being enabled or disabled.

    Level - The level at which the event is enabled.

    MatchAnyKeyword - The bitmask of keywords that the provider uses to 
                      determine the category of events that it writes.

    MatchAllKeyword - This bitmask additionally restricts the category 
                      of events that the provider writes. 

    FilterData - The provider-defined data.

    CallbackContext - The context of the callback that is defined when the provider 
                      called EtwRegister to register itself.

Remarks:

    ETW calls this function to notify provider of enable/disable

--*/
{
    PMCGEN_TRACE_CONTEXT Ctx = (PMCGEN_TRACE_CONTEXT)CallbackContext;
    ULONG Ix;
#ifndef MCGEN_PRIVATE_ENABLE_CALLBACK_V2
    UNREFERENCED_PARAMETER(SourceId);
    UNREFERENCED_PARAMETER(FilterData);
#endif

    if (Ctx == NULL) {
        return;
    }

    switch (ControlCode) {

        case EVENT_CONTROL_CODE_ENABLE_PROVIDER:
            Ctx->Level = Level;
            Ctx->MatchAnyKeyword = MatchAnyKeyword;
            Ctx->MatchAllKeyword = MatchAllKeyword;
            Ctx->IsEnabled = EVENT_CONTROL_CODE_ENABLE_PROVIDER;

            for (Ix = 0; Ix < Ctx->EnableBitsCount; Ix += 1) {
                if (McGenLevelKeywordEnabled(Ctx, Ctx->EnableLevel[Ix], Ctx->EnableKeyWords[Ix]) != FALSE) {
                    Ctx->EnableBitMask[Ix >> 5] |= (1 << (Ix % 32));
                } else {
                    Ctx->EnableBitMask[Ix >> 5] &= ~(1 << (Ix % 32));
                }
            }
            break;

        case EVENT_CONTROL_CODE_DISABLE_PROVIDER:
            Ctx->IsEnabled = EVENT_CONTROL_CODE_DISABLE_PROVIDER;
            Ctx->Level = 0;
            Ctx->MatchAnyKeyword = 0;
            Ctx->MatchAllKeyword = 0;
            if (Ctx->EnableBitsCount > 0) {
                RtlZeroMemory(Ctx->EnableBitMask, (((Ctx->EnableBitsCount - 1) / 32) + 1) * sizeof(ULONG));
            }
            break;
 
        default:
            break;
    }

#ifdef MCGEN_PRIVATE_ENABLE_CALLBACK_V2
    //
    // Call user defined callback
    //
    MCGEN_PRIVATE_ENABLE_CALLBACK_V2(
        SourceId,
        ControlCode,
        Level,
        MatchAnyKeyword,
        MatchAllKeyword,
        FilterData,
        CallbackContext
        );
#endif
   
    return;
}

#endif
#endif // MCGEN_DISABLE_PROVIDER_CODE_GENERATION
//+
// Provider Linux Foundation-Open vSwitch-Userspace Event Count 5
//+
EXTERN_C __declspec(selectany) const GUID Linux_Foundation_Open_vSwitch_Userspace = {0x94208e30, 0x7d3c, 0x43bc, {0x83, 0xdc, 0xec, 0x24, 0xe4, 0xcd, 0xba, 0xd8}};

//
// Channel
//
#define Userspace 0x10

//
// Levels
//
#define OFF 0x10
#define ERR 0x11
#define EMER 0x12
#define WARN 0x13
#define INFO 0x14
#define DBG 0x15

//
// Opcodes
//
#define Sample_Opcode 0xa

//
// Tasks
//
#define Sample_Task 0x64

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR Userspace_Error_Event = {0x64, 0x0, 0x10, 0x2, 0xa, 0x64, 0x8000000000000000};
#define Userspace_Error_Event_value 0x64
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR Userspace_Warning_Event = {0x65, 0x0, 0x10, 0x3, 0xa, 0x64, 0x8000000000000000};
#define Userspace_Warning_Event_value 0x65
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR Userspace_Informational_Event = {0x66, 0x0, 0x10, 0x4, 0xa, 0x64, 0x8000000000000000};
#define Userspace_Informational_Event_value 0x66
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR Userspace_Critical_Event = {0x67, 0x0, 0x10, 0x1, 0xa, 0x64, 0x8000000000000000};
#define Userspace_Critical_Event_value 0x67
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR Userspace_Verbose_Event = {0x68, 0x0, 0x10, 0x5, 0xa, 0x64, 0x8000000000000000};
#define Userspace_Verbose_Event_value 0x68

//
// Note on Generate Code from Manifest for Windows Vista and above
//
//Structures :  are handled as a size and pointer pairs. The macro for the event will have an extra 
//parameter for the size in bytes of the structure. Make sure that your structures have no extra padding.
//
//Strings: There are several cases that can be described in the manifest. For array of variable length 
//strings, the generated code will take the count of characters for the whole array as an input parameter. 
//
//SID No support for array of SIDs, the macro will take a pointer to the SID and use appropriate 
//GetLengthSid function to get the length.
//

//
// Allow disabling of code generation
//
#ifndef MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// Globals 
//


//
// Event Enablement Bits
//

EXTERN_C __declspec(selectany) DECLSPEC_CACHEALIGN ULONG Linux_Foundation_Open_vSwitch_UserspaceEnableBits[1];
EXTERN_C __declspec(selectany) const ULONGLONG Linux_Foundation_Open_vSwitch_UserspaceKeywords[5] = {0x8000000000000000, 0x8000000000000000, 0x8000000000000000, 0x8000000000000000, 0x8000000000000000};
EXTERN_C __declspec(selectany) const UCHAR Linux_Foundation_Open_vSwitch_UserspaceLevels[5] = {2, 3, 4, 1, 5};
EXTERN_C __declspec(selectany) MCGEN_TRACE_CONTEXT Linux_Foundation_Open_vSwitch_Userspace_Context = {0, 0, 0, 0, 0, 0, 0, 0, 5, Linux_Foundation_Open_vSwitch_UserspaceEnableBits, Linux_Foundation_Open_vSwitch_UserspaceKeywords, Linux_Foundation_Open_vSwitch_UserspaceLevels};

EXTERN_C __declspec(selectany) REGHANDLE Linux_Foundation_Open_vSwitch_UserspaceHandle = (REGHANDLE)0;

#if !defined(McGenEventRegisterUnregister)
#define McGenEventRegisterUnregister
#pragma warning(push)
#pragma warning(disable:6103)
DECLSPEC_NOINLINE __inline
ULONG __stdcall
McGenEventRegister(
    _In_ LPCGUID ProviderId,
    _In_opt_ PENABLECALLBACK EnableCallback,
    _In_opt_ PVOID CallbackContext,
    _Inout_ PREGHANDLE RegHandle
    )
/*++

Routine Description:

    This function registers the provider with ETW USER mode.

Arguments:
    ProviderId - Provider ID to be register with ETW.

    EnableCallback - Callback to be used.

    CallbackContext - Context for this provider.

    RegHandle - Pointer to registration handle.

Remarks:

    If the handle != NULL will return ERROR_SUCCESS

--*/
{
    ULONG Error;


    if (*RegHandle) {
        //
        // already registered
        //
        return ERROR_SUCCESS;
    }

    Error = EventRegister( ProviderId, EnableCallback, CallbackContext, RegHandle); 

    return Error;
}
#pragma warning(pop)


DECLSPEC_NOINLINE __inline
ULONG __stdcall
McGenEventUnregister(_Inout_ PREGHANDLE RegHandle)
/*++

Routine Description:

    Unregister from ETW USER mode

Arguments:
            RegHandle this is the pointer to the provider context
Remarks:
            If provider has not been registered, RegHandle == NULL,
            return ERROR_SUCCESS
--*/
{
    ULONG Error;


    if(!(*RegHandle)) {
        //
        // Provider has not registerd
        //
        return ERROR_SUCCESS;
    }

    Error = EventUnregister(*RegHandle); 
    *RegHandle = (REGHANDLE)0;
    
    return Error;
}
#endif
//
// Register with ETW Vista +
//
#ifndef EventRegisterLinux_Foundation_Open_vSwitch_Userspace
#define EventRegisterLinux_Foundation_Open_vSwitch_Userspace() McGenEventRegister(&Linux_Foundation_Open_vSwitch_Userspace, McGenControlCallbackV2, &Linux_Foundation_Open_vSwitch_Userspace_Context, &Linux_Foundation_Open_vSwitch_UserspaceHandle) 
#endif

//
// UnRegister with ETW
//
#ifndef EventUnregisterLinux_Foundation_Open_vSwitch_Userspace
#define EventUnregisterLinux_Foundation_Open_vSwitch_Userspace() McGenEventUnregister(&Linux_Foundation_Open_vSwitch_UserspaceHandle) 
#endif

//
// Enablement check macro for Userspace_Error_Event
//

#define EventEnabledUserspace_Error_Event() ((Linux_Foundation_Open_vSwitch_UserspaceEnableBits[0] & 0x00000001) != 0)

//
// Event Macro for Userspace_Error_Event
//
#define EventWriteUserspace_Error_Event(Prop_UnicodeString)\
        EventEnabledUserspace_Error_Event() ?\
        Template_z(Linux_Foundation_Open_vSwitch_UserspaceHandle, &Userspace_Error_Event, Prop_UnicodeString)\
        : ERROR_SUCCESS\

//
// Enablement check macro for Userspace_Warning_Event
//

#define EventEnabledUserspace_Warning_Event() ((Linux_Foundation_Open_vSwitch_UserspaceEnableBits[0] & 0x00000002) != 0)

//
// Event Macro for Userspace_Warning_Event
//
#define EventWriteUserspace_Warning_Event(Prop_UnicodeString)\
        EventEnabledUserspace_Warning_Event() ?\
        Template_z(Linux_Foundation_Open_vSwitch_UserspaceHandle, &Userspace_Warning_Event, Prop_UnicodeString)\
        : ERROR_SUCCESS\

//
// Enablement check macro for Userspace_Informational_Event
//

#define EventEnabledUserspace_Informational_Event() ((Linux_Foundation_Open_vSwitch_UserspaceEnableBits[0] & 0x00000004) != 0)

//
// Event Macro for Userspace_Informational_Event
//
#define EventWriteUserspace_Informational_Event(Prop_UnicodeString)\
        EventEnabledUserspace_Informational_Event() ?\
        Template_z(Linux_Foundation_Open_vSwitch_UserspaceHandle, &Userspace_Informational_Event, Prop_UnicodeString)\
        : ERROR_SUCCESS\

//
// Enablement check macro for Userspace_Critical_Event
//

#define EventEnabledUserspace_Critical_Event() ((Linux_Foundation_Open_vSwitch_UserspaceEnableBits[0] & 0x00000008) != 0)

//
// Event Macro for Userspace_Critical_Event
//
#define EventWriteUserspace_Critical_Event(Prop_UnicodeString)\
        EventEnabledUserspace_Critical_Event() ?\
        Template_z(Linux_Foundation_Open_vSwitch_UserspaceHandle, &Userspace_Critical_Event, Prop_UnicodeString)\
        : ERROR_SUCCESS\

//
// Enablement check macro for Userspace_Verbose_Event
//

#define EventEnabledUserspace_Verbose_Event() ((Linux_Foundation_Open_vSwitch_UserspaceEnableBits[0] & 0x00000010) != 0)

//
// Event Macro for Userspace_Verbose_Event
//
#define EventWriteUserspace_Verbose_Event(Prop_UnicodeString)\
        EventEnabledUserspace_Verbose_Event() ?\
        Template_z(Linux_Foundation_Open_vSwitch_UserspaceHandle, &Userspace_Verbose_Event, Prop_UnicodeString)\
        : ERROR_SUCCESS\

#endif // MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//+
// Provider Linux Foundation-Open vSwitch-Datapath Event Count 5
//+
EXTERN_C __declspec(selectany) const GUID Linux_Foundation_Open_vSwitch_Datapath = {0x67c8959d, 0x3106, 0x469a, {0x9d, 0x06, 0x83, 0xe9, 0x6e, 0xd7, 0x8b, 0x68}};

//
// Channel
//
#define Datapath 0x10

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR Datapath_Error_Event = {0xc8, 0x0, 0x10, 0x2, 0x0, 0x0, 0x8000000000000000};
#define Datapath_Error_Event_value 0xc8
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR Datapath_Warning_Event = {0xc9, 0x0, 0x10, 0x3, 0x0, 0x0, 0x8000000000000000};
#define Datapath_Warning_Event_value 0xc9
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR Datapath_Informational_Event = {0xca, 0x0, 0x10, 0x4, 0x0, 0x0, 0x8000000000000000};
#define Datapath_Informational_Event_value 0xca
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR Datapath_Critical_Event = {0xcb, 0x0, 0x10, 0x1, 0x0, 0x0, 0x8000000000000000};
#define Datapath_Critical_Event_value 0xcb
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR Datapath_Verbose_Event = {0xcc, 0x0, 0x10, 0x5, 0x0, 0x0, 0x8000000000000000};
#define Datapath_Verbose_Event_value 0xcc

//
// Note on Generate Code from Manifest for Windows Vista and above
//
//Structures :  are handled as a size and pointer pairs. The macro for the event will have an extra 
//parameter for the size in bytes of the structure. Make sure that your structures have no extra padding.
//
//Strings: There are several cases that can be described in the manifest. For array of variable length 
//strings, the generated code will take the count of characters for the whole array as an input parameter. 
//
//SID No support for array of SIDs, the macro will take a pointer to the SID and use appropriate 
//GetLengthSid function to get the length.
//

//
// Allow disabling of code generation
//
#ifndef MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// Globals 
//


//
// Event Enablement Bits
//

EXTERN_C __declspec(selectany) DECLSPEC_CACHEALIGN ULONG Linux_Foundation_Open_vSwitch_DatapathEnableBits[1];
EXTERN_C __declspec(selectany) const ULONGLONG Linux_Foundation_Open_vSwitch_DatapathKeywords[5] = {0x8000000000000000, 0x8000000000000000, 0x8000000000000000, 0x8000000000000000, 0x8000000000000000};
EXTERN_C __declspec(selectany) const UCHAR Linux_Foundation_Open_vSwitch_DatapathLevels[5] = {2, 3, 4, 1, 5};
EXTERN_C __declspec(selectany) MCGEN_TRACE_CONTEXT Linux_Foundation_Open_vSwitch_Datapath_Context = {0, 0, 0, 0, 0, 0, 0, 0, 5, Linux_Foundation_Open_vSwitch_DatapathEnableBits, Linux_Foundation_Open_vSwitch_DatapathKeywords, Linux_Foundation_Open_vSwitch_DatapathLevels};

EXTERN_C __declspec(selectany) REGHANDLE Linux_Foundation_Open_vSwitch_DatapathHandle = (REGHANDLE)0;

#if !defined(McGenEventRegisterUnregister)
#define McGenEventRegisterUnregister
#pragma warning(push)
#pragma warning(disable:6103)
DECLSPEC_NOINLINE __inline
ULONG __stdcall
McGenEventRegister(
    _In_ LPCGUID ProviderId,
    _In_opt_ PENABLECALLBACK EnableCallback,
    _In_opt_ PVOID CallbackContext,
    _Inout_ PREGHANDLE RegHandle
    )
/*++

Routine Description:

    This function registers the provider with ETW USER mode.

Arguments:
    ProviderId - Provider ID to be register with ETW.

    EnableCallback - Callback to be used.

    CallbackContext - Context for this provider.

    RegHandle - Pointer to registration handle.

Remarks:

    If the handle != NULL will return ERROR_SUCCESS

--*/
{
    ULONG Error;


    if (*RegHandle) {
        //
        // already registered
        //
        return ERROR_SUCCESS;
    }

    Error = EventRegister( ProviderId, EnableCallback, CallbackContext, RegHandle); 

    return Error;
}
#pragma warning(pop)


DECLSPEC_NOINLINE __inline
ULONG __stdcall
McGenEventUnregister(_Inout_ PREGHANDLE RegHandle)
/*++

Routine Description:

    Unregister from ETW USER mode

Arguments:
            RegHandle this is the pointer to the provider context
Remarks:
            If provider has not been registered, RegHandle == NULL,
            return ERROR_SUCCESS
--*/
{
    ULONG Error;


    if(!(*RegHandle)) {
        //
        // Provider has not registerd
        //
        return ERROR_SUCCESS;
    }

    Error = EventUnregister(*RegHandle); 
    *RegHandle = (REGHANDLE)0;
    
    return Error;
}
#endif
//
// Register with ETW Vista +
//
#ifndef EventRegisterLinux_Foundation_Open_vSwitch_Datapath
#define EventRegisterLinux_Foundation_Open_vSwitch_Datapath() McGenEventRegister(&Linux_Foundation_Open_vSwitch_Datapath, McGenControlCallbackV2, &Linux_Foundation_Open_vSwitch_Datapath_Context, &Linux_Foundation_Open_vSwitch_DatapathHandle) 
#endif

//
// UnRegister with ETW
//
#ifndef EventUnregisterLinux_Foundation_Open_vSwitch_Datapath
#define EventUnregisterLinux_Foundation_Open_vSwitch_Datapath() McGenEventUnregister(&Linux_Foundation_Open_vSwitch_DatapathHandle) 
#endif

//
// Enablement check macro for Datapath_Error_Event
//

#define EventEnabledDatapath_Error_Event() ((Linux_Foundation_Open_vSwitch_DatapathEnableBits[0] & 0x00000001) != 0)

//
// Event Macro for Datapath_Error_Event
//
#define EventWriteDatapath_Error_Event(Prop_UnicodeString)\
        EventEnabledDatapath_Error_Event() ?\
        Template_z(Linux_Foundation_Open_vSwitch_DatapathHandle, &Datapath_Error_Event, Prop_UnicodeString)\
        : ERROR_SUCCESS\

//
// Enablement check macro for Datapath_Warning_Event
//

#define EventEnabledDatapath_Warning_Event() ((Linux_Foundation_Open_vSwitch_DatapathEnableBits[0] & 0x00000002) != 0)

//
// Event Macro for Datapath_Warning_Event
//
#define EventWriteDatapath_Warning_Event(Prop_UnicodeString)\
        EventEnabledDatapath_Warning_Event() ?\
        Template_z(Linux_Foundation_Open_vSwitch_DatapathHandle, &Datapath_Warning_Event, Prop_UnicodeString)\
        : ERROR_SUCCESS\

//
// Enablement check macro for Datapath_Informational_Event
//

#define EventEnabledDatapath_Informational_Event() ((Linux_Foundation_Open_vSwitch_DatapathEnableBits[0] & 0x00000004) != 0)

//
// Event Macro for Datapath_Informational_Event
//
#define EventWriteDatapath_Informational_Event(Prop_UnicodeString)\
        EventEnabledDatapath_Informational_Event() ?\
        Template_z(Linux_Foundation_Open_vSwitch_DatapathHandle, &Datapath_Informational_Event, Prop_UnicodeString)\
        : ERROR_SUCCESS\

//
// Enablement check macro for Datapath_Critical_Event
//

#define EventEnabledDatapath_Critical_Event() ((Linux_Foundation_Open_vSwitch_DatapathEnableBits[0] & 0x00000008) != 0)

//
// Event Macro for Datapath_Critical_Event
//
#define EventWriteDatapath_Critical_Event(Prop_UnicodeString)\
        EventEnabledDatapath_Critical_Event() ?\
        Template_z(Linux_Foundation_Open_vSwitch_DatapathHandle, &Datapath_Critical_Event, Prop_UnicodeString)\
        : ERROR_SUCCESS\

//
// Enablement check macro for Datapath_Verbose_Event
//

#define EventEnabledDatapath_Verbose_Event() ((Linux_Foundation_Open_vSwitch_DatapathEnableBits[0] & 0x00000010) != 0)

//
// Event Macro for Datapath_Verbose_Event
//
#define EventWriteDatapath_Verbose_Event(Prop_UnicodeString)\
        EventEnabledDatapath_Verbose_Event() ?\
        Template_z(Linux_Foundation_Open_vSwitch_DatapathHandle, &Datapath_Verbose_Event, Prop_UnicodeString)\
        : ERROR_SUCCESS\

#endif // MCGEN_DISABLE_PROVIDER_CODE_GENERATION


//
// Allow Diasabling of code generation
//
#ifndef MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// Template Functions 
//
//
//Template from manifest : T_UnicodeString
//
#ifndef Template_z_def
#define Template_z_def
ETW_INLINE
ULONG
Template_z(
    _In_ REGHANDLE RegHandle,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_opt_ PCWSTR  _Arg0
    )
{
#define ARGUMENT_COUNT_z 1

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_z];

    EventDataDescCreate(&EventData[0], 
                        (_Arg0 != NULL) ? _Arg0 : L"NULL",
                        (_Arg0 != NULL) ? (ULONG)((wcslen(_Arg0) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    return EventWrite(RegHandle, Descriptor, ARGUMENT_COUNT_z, EventData);
}
#endif

#endif // MCGEN_DISABLE_PROVIDER_CODE_GENERATION

#if defined(__cplusplus)
};
#endif

#define MSG_Linux_Foundation_Open_vSwitch_Userspace_opcode_Sample_Opcode_message 0x3000000AL
#define MSG_level_Critical                   0x50000001L
#define MSG_level_Error                      0x50000002L
#define MSG_level_Warning                    0x50000003L
#define MSG_level_Informational              0x50000004L
#define MSG_level_Verbose                    0x50000005L
#define MSG_Linux_Foundation_Open_vSwitch_Userspace_task_Sample_Task_message 0x70000064L
#define MSG_Linux_Foundation_Open_vSwitch_Userspace_event_100_message 0xB0000064L
#define MSG_Linux_Foundation_Open_vSwitch_Userspace_event_101_message 0xB0000065L
#define MSG_Linux_Foundation_Open_vSwitch_Userspace_event_102_message 0xB0000066L
#define MSG_Linux_Foundation_Open_vSwitch_Userspace_event_103_message 0xB0000067L
#define MSG_Linux_Foundation_Open_vSwitch_Userspace_event_104_message 0xB0000068L
#define MSG_Linux_Foundation_Open_vSwitch_Datapath_event_200_message 0xB10000C8L
#define MSG_Linux_Foundation_Open_vSwitch_Datapath_event_201_message 0xB10000C9L
#define MSG_Linux_Foundation_Open_vSwitch_Datapath_event_202_message 0xB10000CAL
#define MSG_Linux_Foundation_Open_vSwitch_Datapath_event_203_message 0xB10000CBL
#define MSG_Linux_Foundation_Open_vSwitch_Datapath_event_204_message 0xB10000CCL
